/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Tue Jul 24 21:53:55 2012
**      by: Qt User Interface Compiler version 4.8.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QGridLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>
#include "tabwidget.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionOpenFile;
    QAction *actionSaveFile;
    QAction *actionSaveAs;
    QAction *actionExitApp;
    QAction *actionHelpContent;
    QAction *actionAboutApp;
    QAction *actionNewFile;
    QAction *actionReloadFromDisk;
    QAction *actionSaveAll;
    QAction *actionClose;
    QAction *actionCloseAll;
    QAction *actionCloseAllButActiveDocument;
    QAction *actionPrint;
    QAction *actionPrintNow;
    QAction *actionOpenAllRecentFiles;
    QAction *actionEmptyRecentFilesList;
    QAction *actionRecentFiles;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionCut;
    QAction *actionCopy;
    QAction *actionPaste;
    QAction *actionDelete;
    QAction *actionSelectAll;
    QAction *actionColumnMode;
    QAction *actionColumnEditor;
    QAction *actionCharacterPanel;
    QAction *actionClipboardHistory;
    QAction *actionSetReadOnly;
    QAction *actionClearReadOnlyFlag;
    QAction *actionCurrentFullFilePathToClipboard;
    QAction *actionCurrentFileNameToClipboard;
    QAction *actionCurrentDirectoryPathToClipboard;
    QAction *actionIncreaseLineIndent;
    QAction *actionDecreaseLineIndent;
    QAction *actionUppercase;
    QAction *actionLowercase;
    QAction *actionDuplicateCurrentLine;
    QAction *actionSplitLines;
    QAction *actionJoinLines;
    QAction *actionMoveUpCurrentLine;
    QAction *actionMoveDownCurrentLine;
    QAction *actionToggleBlockComment;
    QAction *actionBlockComment;
    QAction *actionBlockUncomment;
    QAction *actionStreamComment;
    QAction *actionFunctionCompletion;
    QAction *actionWordCompletion;
    QAction *actionFunctionParametersHint;
    QAction *actionWindowsFormat;
    QAction *actionUNIXFormat;
    QAction *actionMacFormat;
    QAction *actionTrimTrailingSpace;
    QAction *actionTrimLeadingSpace;
    QAction *actionTrimLeadingAndTrailingSpace;
    QAction *actionEOLToSpace;
    QAction *actionRemoveUnnecessaryBlankAndEOL;
    QAction *actionTABToSpace;
    QAction *actionSpaceToTAB;
    QAction *actionPasteHTMLContent;
    QAction *actionPasteRTFContent;
    QAction *actionCopyBinaryContent;
    QAction *actionCutBinaryContent;
    QAction *actionPasteBinaryContent;
    QAction *actionFind;
    QAction *actionFindInFiles;
    QAction *actionFindNext;
    QAction *actionFindPrevious;
    QAction *actionSelectAndFindNext;
    QAction *actionSelectAndFindPrevious;
    QAction *actionFindVolatieNext;
    QAction *actionFindVolatiePrevious;
    QAction *actionReplace;
    QAction *actionIncrementalSearch;
    QAction *actionSearchResultsWindow;
    QAction *actionNextSearchResult;
    QAction *actionPreviousSearchResult;
    QAction *actionGoTo;
    QAction *actionGoToMatchingBrace;
    QAction *actionFindCharactersInRange;
    QAction *actionUsing1stStyle;
    QAction *actionUsing2ndStyle;
    QAction *actionUsing3rdStyle;
    QAction *actionUsing4thStyle;
    QAction *actionUsing5thStyle;
    QAction *actionClear1stStyle;
    QAction *actionClear2ndStyle;
    QAction *actionClear3rdStyle;
    QAction *actionClear4thStyle;
    QAction *actionClear5thStyle;
    QAction *actionClearAllStyle;
    QAction *actionJumpUp1stStyle;
    QAction *actionJumpUp2ndStyle;
    QAction *actionJumpUp3rdStyle;
    QAction *actionJumpUp4thStyle;
    QAction *actionJumpUp5thStyle;
    QAction *actionJumpUpFindStyle;
    QAction *actionJumpDown1stStyle;
    QAction *actionJumpDown2ndStyle;
    QAction *actionJumpDown3rdStyle;
    QAction *actionJumpDown4thStyle;
    QAction *actionJumpDown5thStyle;
    QAction *actionJumpDownFindStyle;
    QAction *actionToggleBookmark;
    QAction *actionNextBookmark;
    QAction *actionPreviousBookmark;
    QAction *actionClearAllBookmarks;
    QAction *actionCutBookmarkedLines;
    QAction *actionCopyBookmarkedLines;
    QAction *actionPasteToReplaceBookmarkedLines;
    QAction *actionRemoveBookmarkedLines;
    QAction *actionRemoveUnmarkedLines;
    QAction *actionInverseBookmark;
    QAction *actionRegistration;
    QAction *actionSelectExtensionItem;
    QAction *actionStartRecording;
    QAction *actionAbortRecording;
    QAction *actionSaveLastRecording;
    QAction *actionReplayLastRecording;
    QAction *actionShowExtensionEditor;
    QAction *actionEditCommands;
    QAction *actionEditSnippets;
    QAction *actionReloadExtensions;
    QAction *action_Plugins;
    QAction *actionDForDSoftwareHome;
    QAction *actionAinesmileProductPage;
    QAction *actionAlwaysOnTop;
    QAction *actionToggleFullScreenMode;
    QAction *actionPostIt;
    QAction *actionMove_Clone_Current_Document;
    QAction *actionWordWrap;
    QAction *actionFocusOnAnotherView;
    QAction *actionHideLines;
    QAction *actionUserDefinedDialog;
    QAction *actionFoldAll;
    QAction *actionUnfoldAll;
    QAction *actionCollapseCurrentLevel;
    QAction *actionUncollapseCurrentLevel;
    QAction *actionCollapseLevel;
    QAction *actionUnCollapseLevel;
    QAction *actionSummary;
    QAction *actionProject;
    QAction *actionSynchronizeVerticalScrolling;
    QAction *actionSynchronizeHorizontalScrolling;
    QAction *actionTextDirectionRTL;
    QAction *actionTextDirectionLTR;
    QAction *actionEncodeInANSI;
    QAction *actionEncodeInUTF8WithoutBOM;
    QAction *actionEncodeInUTF8;
    QAction *actionEncodeInUCS2BigEndian;
    QAction *actionEncodeInUCS2LittleEndian;
    QAction *actionCharacterSets;
    QAction *actionConvertToANSI;
    QAction *actionConvertToUTF8WithoutBOM;
    QAction *actionConvertToUTF8;
    QAction *actionConvertToUCS2BigEndian;
    QAction *actionConvertToUCS2LittleEndian;
    QAction *actionShowWhiteSpaceAndTAB;
    QAction *actionShowEndOfLine;
    QAction *actionShowAllCharacters;
    QAction *actionShowIndentGuide;
    QAction *actionShowWrapSymbol;
    QAction *actionZoomIn;
    QAction *actionZoomOut;
    QAction *actionRestoreDefaultZoom;
    QAction *actionTool;
    QAction *actionPreferences;
    QAction *actionExternal_Tools;
    QAction *actionLanguage;
    QAction *actionPluginManager;
    QAction *actionWindowsList;
    QAction *actionCloseAllDocuments;
    QAction *actionOpenProject;
    QAction *actionCloseProject;
    QAction *actionNewProject;
    QWidget *centralWidget;
    QGridLayout *gridLayout;
    TabWidget *tabWidget;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuHelp;
    QMenu *menuEdit;
    QMenu *menuCopyToClipboard;
    QMenu *menuIndent;
    QMenu *menuConvert_case_to;
    QMenu *menuLineOperations;
    QMenu *menuComment_Uncomment;
    QMenu *menuAutoCompletion;
    QMenu *menuEOLConversion;
    QMenu *menuBlankOperations;
    QMenu *menuPasteSpecial;
    QMenu *menuSearch;
    QMenu *menuMarkAll;
    QMenu *menuUnmarkAll;
    QMenu *menuJumpUp;
    QMenu *menuJumpDown;
    QMenu *menuBookmark;
    QMenu *menuExtension;
    QMenu *menuMacros;
    QMenu *menuExtensionEditor;
    QMenu *menuView;
    QMenu *menuShowSymbol;
    QMenu *menuZoom;
    QMenu *menuEn_coding;
    QMenu *menuTool;
    QMenu *menuPlugins;
    QMenu *menuWindow;
    QMenu *menuProject;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1298, 795);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/rc/Ainesmile.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        actionOpenFile = new QAction(MainWindow);
        actionOpenFile->setObjectName(QString::fromUtf8("actionOpenFile"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/rc/image/fileopen.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpenFile->setIcon(icon1);
        actionSaveFile = new QAction(MainWindow);
        actionSaveFile->setObjectName(QString::fromUtf8("actionSaveFile"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/rc/image/filesave.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveFile->setIcon(icon2);
        actionSaveAs = new QAction(MainWindow);
        actionSaveAs->setObjectName(QString::fromUtf8("actionSaveAs"));
        actionExitApp = new QAction(MainWindow);
        actionExitApp->setObjectName(QString::fromUtf8("actionExitApp"));
        actionHelpContent = new QAction(MainWindow);
        actionHelpContent->setObjectName(QString::fromUtf8("actionHelpContent"));
        actionAboutApp = new QAction(MainWindow);
        actionAboutApp->setObjectName(QString::fromUtf8("actionAboutApp"));
        actionNewFile = new QAction(MainWindow);
        actionNewFile->setObjectName(QString::fromUtf8("actionNewFile"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/rc/image/filenew.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionNewFile->setIcon(icon3);
        actionReloadFromDisk = new QAction(MainWindow);
        actionReloadFromDisk->setObjectName(QString::fromUtf8("actionReloadFromDisk"));
        actionSaveAll = new QAction(MainWindow);
        actionSaveAll->setObjectName(QString::fromUtf8("actionSaveAll"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/rc/image/filesaveall.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSaveAll->setIcon(icon4);
        actionClose = new QAction(MainWindow);
        actionClose->setObjectName(QString::fromUtf8("actionClose"));
        actionCloseAll = new QAction(MainWindow);
        actionCloseAll->setObjectName(QString::fromUtf8("actionCloseAll"));
        actionCloseAllButActiveDocument = new QAction(MainWindow);
        actionCloseAllButActiveDocument->setObjectName(QString::fromUtf8("actionCloseAllButActiveDocument"));
        actionPrint = new QAction(MainWindow);
        actionPrint->setObjectName(QString::fromUtf8("actionPrint"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/rc/image/fileprint.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPrint->setIcon(icon5);
        actionPrintNow = new QAction(MainWindow);
        actionPrintNow->setObjectName(QString::fromUtf8("actionPrintNow"));
        actionOpenAllRecentFiles = new QAction(MainWindow);
        actionOpenAllRecentFiles->setObjectName(QString::fromUtf8("actionOpenAllRecentFiles"));
        actionEmptyRecentFilesList = new QAction(MainWindow);
        actionEmptyRecentFilesList->setObjectName(QString::fromUtf8("actionEmptyRecentFilesList"));
        actionRecentFiles = new QAction(MainWindow);
        actionRecentFiles->setObjectName(QString::fromUtf8("actionRecentFiles"));
        actionUndo = new QAction(MainWindow);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/rc/image/undo.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUndo->setIcon(icon6);
        actionRedo = new QAction(MainWindow);
        actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/rc/image/redo.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRedo->setIcon(icon7);
        actionCut = new QAction(MainWindow);
        actionCut->setObjectName(QString::fromUtf8("actionCut"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/rc/image/editcut.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCut->setIcon(icon8);
        actionCopy = new QAction(MainWindow);
        actionCopy->setObjectName(QString::fromUtf8("actionCopy"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/rc/image/editcopy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCopy->setIcon(icon9);
        actionPaste = new QAction(MainWindow);
        actionPaste->setObjectName(QString::fromUtf8("actionPaste"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/rc/image/editpaste.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPaste->setIcon(icon10);
        actionDelete = new QAction(MainWindow);
        actionDelete->setObjectName(QString::fromUtf8("actionDelete"));
        actionSelectAll = new QAction(MainWindow);
        actionSelectAll->setObjectName(QString::fromUtf8("actionSelectAll"));
        actionColumnMode = new QAction(MainWindow);
        actionColumnMode->setObjectName(QString::fromUtf8("actionColumnMode"));
        actionColumnEditor = new QAction(MainWindow);
        actionColumnEditor->setObjectName(QString::fromUtf8("actionColumnEditor"));
        actionCharacterPanel = new QAction(MainWindow);
        actionCharacterPanel->setObjectName(QString::fromUtf8("actionCharacterPanel"));
        actionClipboardHistory = new QAction(MainWindow);
        actionClipboardHistory->setObjectName(QString::fromUtf8("actionClipboardHistory"));
        actionSetReadOnly = new QAction(MainWindow);
        actionSetReadOnly->setObjectName(QString::fromUtf8("actionSetReadOnly"));
        actionClearReadOnlyFlag = new QAction(MainWindow);
        actionClearReadOnlyFlag->setObjectName(QString::fromUtf8("actionClearReadOnlyFlag"));
        actionCurrentFullFilePathToClipboard = new QAction(MainWindow);
        actionCurrentFullFilePathToClipboard->setObjectName(QString::fromUtf8("actionCurrentFullFilePathToClipboard"));
        actionCurrentFileNameToClipboard = new QAction(MainWindow);
        actionCurrentFileNameToClipboard->setObjectName(QString::fromUtf8("actionCurrentFileNameToClipboard"));
        actionCurrentDirectoryPathToClipboard = new QAction(MainWindow);
        actionCurrentDirectoryPathToClipboard->setObjectName(QString::fromUtf8("actionCurrentDirectoryPathToClipboard"));
        actionIncreaseLineIndent = new QAction(MainWindow);
        actionIncreaseLineIndent->setObjectName(QString::fromUtf8("actionIncreaseLineIndent"));
        actionDecreaseLineIndent = new QAction(MainWindow);
        actionDecreaseLineIndent->setObjectName(QString::fromUtf8("actionDecreaseLineIndent"));
        actionUppercase = new QAction(MainWindow);
        actionUppercase->setObjectName(QString::fromUtf8("actionUppercase"));
        actionLowercase = new QAction(MainWindow);
        actionLowercase->setObjectName(QString::fromUtf8("actionLowercase"));
        actionDuplicateCurrentLine = new QAction(MainWindow);
        actionDuplicateCurrentLine->setObjectName(QString::fromUtf8("actionDuplicateCurrentLine"));
        actionSplitLines = new QAction(MainWindow);
        actionSplitLines->setObjectName(QString::fromUtf8("actionSplitLines"));
        actionJoinLines = new QAction(MainWindow);
        actionJoinLines->setObjectName(QString::fromUtf8("actionJoinLines"));
        actionMoveUpCurrentLine = new QAction(MainWindow);
        actionMoveUpCurrentLine->setObjectName(QString::fromUtf8("actionMoveUpCurrentLine"));
        actionMoveDownCurrentLine = new QAction(MainWindow);
        actionMoveDownCurrentLine->setObjectName(QString::fromUtf8("actionMoveDownCurrentLine"));
        actionToggleBlockComment = new QAction(MainWindow);
        actionToggleBlockComment->setObjectName(QString::fromUtf8("actionToggleBlockComment"));
        actionBlockComment = new QAction(MainWindow);
        actionBlockComment->setObjectName(QString::fromUtf8("actionBlockComment"));
        actionBlockUncomment = new QAction(MainWindow);
        actionBlockUncomment->setObjectName(QString::fromUtf8("actionBlockUncomment"));
        actionStreamComment = new QAction(MainWindow);
        actionStreamComment->setObjectName(QString::fromUtf8("actionStreamComment"));
        actionFunctionCompletion = new QAction(MainWindow);
        actionFunctionCompletion->setObjectName(QString::fromUtf8("actionFunctionCompletion"));
        actionWordCompletion = new QAction(MainWindow);
        actionWordCompletion->setObjectName(QString::fromUtf8("actionWordCompletion"));
        actionFunctionParametersHint = new QAction(MainWindow);
        actionFunctionParametersHint->setObjectName(QString::fromUtf8("actionFunctionParametersHint"));
        actionWindowsFormat = new QAction(MainWindow);
        actionWindowsFormat->setObjectName(QString::fromUtf8("actionWindowsFormat"));
        actionWindowsFormat->setCheckable(true);
        actionUNIXFormat = new QAction(MainWindow);
        actionUNIXFormat->setObjectName(QString::fromUtf8("actionUNIXFormat"));
        actionUNIXFormat->setCheckable(true);
        actionMacFormat = new QAction(MainWindow);
        actionMacFormat->setObjectName(QString::fromUtf8("actionMacFormat"));
        actionMacFormat->setCheckable(true);
        actionTrimTrailingSpace = new QAction(MainWindow);
        actionTrimTrailingSpace->setObjectName(QString::fromUtf8("actionTrimTrailingSpace"));
        actionTrimLeadingSpace = new QAction(MainWindow);
        actionTrimLeadingSpace->setObjectName(QString::fromUtf8("actionTrimLeadingSpace"));
        actionTrimLeadingAndTrailingSpace = new QAction(MainWindow);
        actionTrimLeadingAndTrailingSpace->setObjectName(QString::fromUtf8("actionTrimLeadingAndTrailingSpace"));
        actionEOLToSpace = new QAction(MainWindow);
        actionEOLToSpace->setObjectName(QString::fromUtf8("actionEOLToSpace"));
        actionRemoveUnnecessaryBlankAndEOL = new QAction(MainWindow);
        actionRemoveUnnecessaryBlankAndEOL->setObjectName(QString::fromUtf8("actionRemoveUnnecessaryBlankAndEOL"));
        actionTABToSpace = new QAction(MainWindow);
        actionTABToSpace->setObjectName(QString::fromUtf8("actionTABToSpace"));
        actionSpaceToTAB = new QAction(MainWindow);
        actionSpaceToTAB->setObjectName(QString::fromUtf8("actionSpaceToTAB"));
        actionPasteHTMLContent = new QAction(MainWindow);
        actionPasteHTMLContent->setObjectName(QString::fromUtf8("actionPasteHTMLContent"));
        actionPasteRTFContent = new QAction(MainWindow);
        actionPasteRTFContent->setObjectName(QString::fromUtf8("actionPasteRTFContent"));
        actionCopyBinaryContent = new QAction(MainWindow);
        actionCopyBinaryContent->setObjectName(QString::fromUtf8("actionCopyBinaryContent"));
        actionCutBinaryContent = new QAction(MainWindow);
        actionCutBinaryContent->setObjectName(QString::fromUtf8("actionCutBinaryContent"));
        actionPasteBinaryContent = new QAction(MainWindow);
        actionPasteBinaryContent->setObjectName(QString::fromUtf8("actionPasteBinaryContent"));
        actionFind = new QAction(MainWindow);
        actionFind->setObjectName(QString::fromUtf8("actionFind"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/rc/image/filefind.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFind->setIcon(icon11);
        actionFindInFiles = new QAction(MainWindow);
        actionFindInFiles->setObjectName(QString::fromUtf8("actionFindInFiles"));
        actionFindNext = new QAction(MainWindow);
        actionFindNext->setObjectName(QString::fromUtf8("actionFindNext"));
        actionFindPrevious = new QAction(MainWindow);
        actionFindPrevious->setObjectName(QString::fromUtf8("actionFindPrevious"));
        actionSelectAndFindNext = new QAction(MainWindow);
        actionSelectAndFindNext->setObjectName(QString::fromUtf8("actionSelectAndFindNext"));
        actionSelectAndFindPrevious = new QAction(MainWindow);
        actionSelectAndFindPrevious->setObjectName(QString::fromUtf8("actionSelectAndFindPrevious"));
        actionFindVolatieNext = new QAction(MainWindow);
        actionFindVolatieNext->setObjectName(QString::fromUtf8("actionFindVolatieNext"));
        actionFindVolatiePrevious = new QAction(MainWindow);
        actionFindVolatiePrevious->setObjectName(QString::fromUtf8("actionFindVolatiePrevious"));
        actionReplace = new QAction(MainWindow);
        actionReplace->setObjectName(QString::fromUtf8("actionReplace"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/rc/image/searchreplace.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReplace->setIcon(icon12);
        actionIncrementalSearch = new QAction(MainWindow);
        actionIncrementalSearch->setObjectName(QString::fromUtf8("actionIncrementalSearch"));
        actionSearchResultsWindow = new QAction(MainWindow);
        actionSearchResultsWindow->setObjectName(QString::fromUtf8("actionSearchResultsWindow"));
        actionNextSearchResult = new QAction(MainWindow);
        actionNextSearchResult->setObjectName(QString::fromUtf8("actionNextSearchResult"));
        actionPreviousSearchResult = new QAction(MainWindow);
        actionPreviousSearchResult->setObjectName(QString::fromUtf8("actionPreviousSearchResult"));
        actionGoTo = new QAction(MainWindow);
        actionGoTo->setObjectName(QString::fromUtf8("actionGoTo"));
        actionGoToMatchingBrace = new QAction(MainWindow);
        actionGoToMatchingBrace->setObjectName(QString::fromUtf8("actionGoToMatchingBrace"));
        actionFindCharactersInRange = new QAction(MainWindow);
        actionFindCharactersInRange->setObjectName(QString::fromUtf8("actionFindCharactersInRange"));
        actionUsing1stStyle = new QAction(MainWindow);
        actionUsing1stStyle->setObjectName(QString::fromUtf8("actionUsing1stStyle"));
        actionUsing2ndStyle = new QAction(MainWindow);
        actionUsing2ndStyle->setObjectName(QString::fromUtf8("actionUsing2ndStyle"));
        actionUsing3rdStyle = new QAction(MainWindow);
        actionUsing3rdStyle->setObjectName(QString::fromUtf8("actionUsing3rdStyle"));
        actionUsing4thStyle = new QAction(MainWindow);
        actionUsing4thStyle->setObjectName(QString::fromUtf8("actionUsing4thStyle"));
        actionUsing5thStyle = new QAction(MainWindow);
        actionUsing5thStyle->setObjectName(QString::fromUtf8("actionUsing5thStyle"));
        actionClear1stStyle = new QAction(MainWindow);
        actionClear1stStyle->setObjectName(QString::fromUtf8("actionClear1stStyle"));
        actionClear2ndStyle = new QAction(MainWindow);
        actionClear2ndStyle->setObjectName(QString::fromUtf8("actionClear2ndStyle"));
        actionClear3rdStyle = new QAction(MainWindow);
        actionClear3rdStyle->setObjectName(QString::fromUtf8("actionClear3rdStyle"));
        actionClear4thStyle = new QAction(MainWindow);
        actionClear4thStyle->setObjectName(QString::fromUtf8("actionClear4thStyle"));
        actionClear5thStyle = new QAction(MainWindow);
        actionClear5thStyle->setObjectName(QString::fromUtf8("actionClear5thStyle"));
        actionClearAllStyle = new QAction(MainWindow);
        actionClearAllStyle->setObjectName(QString::fromUtf8("actionClearAllStyle"));
        actionJumpUp1stStyle = new QAction(MainWindow);
        actionJumpUp1stStyle->setObjectName(QString::fromUtf8("actionJumpUp1stStyle"));
        actionJumpUp2ndStyle = new QAction(MainWindow);
        actionJumpUp2ndStyle->setObjectName(QString::fromUtf8("actionJumpUp2ndStyle"));
        actionJumpUp3rdStyle = new QAction(MainWindow);
        actionJumpUp3rdStyle->setObjectName(QString::fromUtf8("actionJumpUp3rdStyle"));
        actionJumpUp4thStyle = new QAction(MainWindow);
        actionJumpUp4thStyle->setObjectName(QString::fromUtf8("actionJumpUp4thStyle"));
        actionJumpUp5thStyle = new QAction(MainWindow);
        actionJumpUp5thStyle->setObjectName(QString::fromUtf8("actionJumpUp5thStyle"));
        actionJumpUpFindStyle = new QAction(MainWindow);
        actionJumpUpFindStyle->setObjectName(QString::fromUtf8("actionJumpUpFindStyle"));
        actionJumpDown1stStyle = new QAction(MainWindow);
        actionJumpDown1stStyle->setObjectName(QString::fromUtf8("actionJumpDown1stStyle"));
        actionJumpDown2ndStyle = new QAction(MainWindow);
        actionJumpDown2ndStyle->setObjectName(QString::fromUtf8("actionJumpDown2ndStyle"));
        actionJumpDown3rdStyle = new QAction(MainWindow);
        actionJumpDown3rdStyle->setObjectName(QString::fromUtf8("actionJumpDown3rdStyle"));
        actionJumpDown4thStyle = new QAction(MainWindow);
        actionJumpDown4thStyle->setObjectName(QString::fromUtf8("actionJumpDown4thStyle"));
        actionJumpDown5thStyle = new QAction(MainWindow);
        actionJumpDown5thStyle->setObjectName(QString::fromUtf8("actionJumpDown5thStyle"));
        actionJumpDownFindStyle = new QAction(MainWindow);
        actionJumpDownFindStyle->setObjectName(QString::fromUtf8("actionJumpDownFindStyle"));
        actionToggleBookmark = new QAction(MainWindow);
        actionToggleBookmark->setObjectName(QString::fromUtf8("actionToggleBookmark"));
        actionNextBookmark = new QAction(MainWindow);
        actionNextBookmark->setObjectName(QString::fromUtf8("actionNextBookmark"));
        actionPreviousBookmark = new QAction(MainWindow);
        actionPreviousBookmark->setObjectName(QString::fromUtf8("actionPreviousBookmark"));
        actionClearAllBookmarks = new QAction(MainWindow);
        actionClearAllBookmarks->setObjectName(QString::fromUtf8("actionClearAllBookmarks"));
        actionCutBookmarkedLines = new QAction(MainWindow);
        actionCutBookmarkedLines->setObjectName(QString::fromUtf8("actionCutBookmarkedLines"));
        actionCopyBookmarkedLines = new QAction(MainWindow);
        actionCopyBookmarkedLines->setObjectName(QString::fromUtf8("actionCopyBookmarkedLines"));
        actionPasteToReplaceBookmarkedLines = new QAction(MainWindow);
        actionPasteToReplaceBookmarkedLines->setObjectName(QString::fromUtf8("actionPasteToReplaceBookmarkedLines"));
        actionRemoveBookmarkedLines = new QAction(MainWindow);
        actionRemoveBookmarkedLines->setObjectName(QString::fromUtf8("actionRemoveBookmarkedLines"));
        actionRemoveUnmarkedLines = new QAction(MainWindow);
        actionRemoveUnmarkedLines->setObjectName(QString::fromUtf8("actionRemoveUnmarkedLines"));
        actionInverseBookmark = new QAction(MainWindow);
        actionInverseBookmark->setObjectName(QString::fromUtf8("actionInverseBookmark"));
        actionRegistration = new QAction(MainWindow);
        actionRegistration->setObjectName(QString::fromUtf8("actionRegistration"));
        actionSelectExtensionItem = new QAction(MainWindow);
        actionSelectExtensionItem->setObjectName(QString::fromUtf8("actionSelectExtensionItem"));
        actionStartRecording = new QAction(MainWindow);
        actionStartRecording->setObjectName(QString::fromUtf8("actionStartRecording"));
        actionAbortRecording = new QAction(MainWindow);
        actionAbortRecording->setObjectName(QString::fromUtf8("actionAbortRecording"));
        actionSaveLastRecording = new QAction(MainWindow);
        actionSaveLastRecording->setObjectName(QString::fromUtf8("actionSaveLastRecording"));
        actionReplayLastRecording = new QAction(MainWindow);
        actionReplayLastRecording->setObjectName(QString::fromUtf8("actionReplayLastRecording"));
        actionShowExtensionEditor = new QAction(MainWindow);
        actionShowExtensionEditor->setObjectName(QString::fromUtf8("actionShowExtensionEditor"));
        actionEditCommands = new QAction(MainWindow);
        actionEditCommands->setObjectName(QString::fromUtf8("actionEditCommands"));
        actionEditSnippets = new QAction(MainWindow);
        actionEditSnippets->setObjectName(QString::fromUtf8("actionEditSnippets"));
        actionReloadExtensions = new QAction(MainWindow);
        actionReloadExtensions->setObjectName(QString::fromUtf8("actionReloadExtensions"));
        action_Plugins = new QAction(MainWindow);
        action_Plugins->setObjectName(QString::fromUtf8("action_Plugins"));
        actionDForDSoftwareHome = new QAction(MainWindow);
        actionDForDSoftwareHome->setObjectName(QString::fromUtf8("actionDForDSoftwareHome"));
        actionAinesmileProductPage = new QAction(MainWindow);
        actionAinesmileProductPage->setObjectName(QString::fromUtf8("actionAinesmileProductPage"));
        actionAlwaysOnTop = new QAction(MainWindow);
        actionAlwaysOnTop->setObjectName(QString::fromUtf8("actionAlwaysOnTop"));
        actionToggleFullScreenMode = new QAction(MainWindow);
        actionToggleFullScreenMode->setObjectName(QString::fromUtf8("actionToggleFullScreenMode"));
        actionPostIt = new QAction(MainWindow);
        actionPostIt->setObjectName(QString::fromUtf8("actionPostIt"));
        actionMove_Clone_Current_Document = new QAction(MainWindow);
        actionMove_Clone_Current_Document->setObjectName(QString::fromUtf8("actionMove_Clone_Current_Document"));
        actionWordWrap = new QAction(MainWindow);
        actionWordWrap->setObjectName(QString::fromUtf8("actionWordWrap"));
        actionFocusOnAnotherView = new QAction(MainWindow);
        actionFocusOnAnotherView->setObjectName(QString::fromUtf8("actionFocusOnAnotherView"));
        actionHideLines = new QAction(MainWindow);
        actionHideLines->setObjectName(QString::fromUtf8("actionHideLines"));
        actionUserDefinedDialog = new QAction(MainWindow);
        actionUserDefinedDialog->setObjectName(QString::fromUtf8("actionUserDefinedDialog"));
        actionFoldAll = new QAction(MainWindow);
        actionFoldAll->setObjectName(QString::fromUtf8("actionFoldAll"));
        actionUnfoldAll = new QAction(MainWindow);
        actionUnfoldAll->setObjectName(QString::fromUtf8("actionUnfoldAll"));
        actionCollapseCurrentLevel = new QAction(MainWindow);
        actionCollapseCurrentLevel->setObjectName(QString::fromUtf8("actionCollapseCurrentLevel"));
        actionUncollapseCurrentLevel = new QAction(MainWindow);
        actionUncollapseCurrentLevel->setObjectName(QString::fromUtf8("actionUncollapseCurrentLevel"));
        actionCollapseLevel = new QAction(MainWindow);
        actionCollapseLevel->setObjectName(QString::fromUtf8("actionCollapseLevel"));
        actionUnCollapseLevel = new QAction(MainWindow);
        actionUnCollapseLevel->setObjectName(QString::fromUtf8("actionUnCollapseLevel"));
        actionSummary = new QAction(MainWindow);
        actionSummary->setObjectName(QString::fromUtf8("actionSummary"));
        actionProject = new QAction(MainWindow);
        actionProject->setObjectName(QString::fromUtf8("actionProject"));
        actionSynchronizeVerticalScrolling = new QAction(MainWindow);
        actionSynchronizeVerticalScrolling->setObjectName(QString::fromUtf8("actionSynchronizeVerticalScrolling"));
        actionSynchronizeHorizontalScrolling = new QAction(MainWindow);
        actionSynchronizeHorizontalScrolling->setObjectName(QString::fromUtf8("actionSynchronizeHorizontalScrolling"));
        actionTextDirectionRTL = new QAction(MainWindow);
        actionTextDirectionRTL->setObjectName(QString::fromUtf8("actionTextDirectionRTL"));
        actionTextDirectionLTR = new QAction(MainWindow);
        actionTextDirectionLTR->setObjectName(QString::fromUtf8("actionTextDirectionLTR"));
        actionEncodeInANSI = new QAction(MainWindow);
        actionEncodeInANSI->setObjectName(QString::fromUtf8("actionEncodeInANSI"));
        actionEncodeInUTF8WithoutBOM = new QAction(MainWindow);
        actionEncodeInUTF8WithoutBOM->setObjectName(QString::fromUtf8("actionEncodeInUTF8WithoutBOM"));
        actionEncodeInUTF8 = new QAction(MainWindow);
        actionEncodeInUTF8->setObjectName(QString::fromUtf8("actionEncodeInUTF8"));
        actionEncodeInUCS2BigEndian = new QAction(MainWindow);
        actionEncodeInUCS2BigEndian->setObjectName(QString::fromUtf8("actionEncodeInUCS2BigEndian"));
        actionEncodeInUCS2LittleEndian = new QAction(MainWindow);
        actionEncodeInUCS2LittleEndian->setObjectName(QString::fromUtf8("actionEncodeInUCS2LittleEndian"));
        actionCharacterSets = new QAction(MainWindow);
        actionCharacterSets->setObjectName(QString::fromUtf8("actionCharacterSets"));
        actionConvertToANSI = new QAction(MainWindow);
        actionConvertToANSI->setObjectName(QString::fromUtf8("actionConvertToANSI"));
        actionConvertToUTF8WithoutBOM = new QAction(MainWindow);
        actionConvertToUTF8WithoutBOM->setObjectName(QString::fromUtf8("actionConvertToUTF8WithoutBOM"));
        actionConvertToUTF8 = new QAction(MainWindow);
        actionConvertToUTF8->setObjectName(QString::fromUtf8("actionConvertToUTF8"));
        actionConvertToUCS2BigEndian = new QAction(MainWindow);
        actionConvertToUCS2BigEndian->setObjectName(QString::fromUtf8("actionConvertToUCS2BigEndian"));
        actionConvertToUCS2LittleEndian = new QAction(MainWindow);
        actionConvertToUCS2LittleEndian->setObjectName(QString::fromUtf8("actionConvertToUCS2LittleEndian"));
        actionShowWhiteSpaceAndTAB = new QAction(MainWindow);
        actionShowWhiteSpaceAndTAB->setObjectName(QString::fromUtf8("actionShowWhiteSpaceAndTAB"));
        actionShowEndOfLine = new QAction(MainWindow);
        actionShowEndOfLine->setObjectName(QString::fromUtf8("actionShowEndOfLine"));
        actionShowAllCharacters = new QAction(MainWindow);
        actionShowAllCharacters->setObjectName(QString::fromUtf8("actionShowAllCharacters"));
        actionShowIndentGuide = new QAction(MainWindow);
        actionShowIndentGuide->setObjectName(QString::fromUtf8("actionShowIndentGuide"));
        actionShowWrapSymbol = new QAction(MainWindow);
        actionShowWrapSymbol->setObjectName(QString::fromUtf8("actionShowWrapSymbol"));
        actionZoomIn = new QAction(MainWindow);
        actionZoomIn->setObjectName(QString::fromUtf8("actionZoomIn"));
        actionZoomOut = new QAction(MainWindow);
        actionZoomOut->setObjectName(QString::fromUtf8("actionZoomOut"));
        actionRestoreDefaultZoom = new QAction(MainWindow);
        actionRestoreDefaultZoom->setObjectName(QString::fromUtf8("actionRestoreDefaultZoom"));
        actionTool = new QAction(MainWindow);
        actionTool->setObjectName(QString::fromUtf8("actionTool"));
        actionPreferences = new QAction(MainWindow);
        actionPreferences->setObjectName(QString::fromUtf8("actionPreferences"));
        actionExternal_Tools = new QAction(MainWindow);
        actionExternal_Tools->setObjectName(QString::fromUtf8("actionExternal_Tools"));
        actionLanguage = new QAction(MainWindow);
        actionLanguage->setObjectName(QString::fromUtf8("actionLanguage"));
        actionPluginManager = new QAction(MainWindow);
        actionPluginManager->setObjectName(QString::fromUtf8("actionPluginManager"));
        actionWindowsList = new QAction(MainWindow);
        actionWindowsList->setObjectName(QString::fromUtf8("actionWindowsList"));
        actionCloseAllDocuments = new QAction(MainWindow);
        actionCloseAllDocuments->setObjectName(QString::fromUtf8("actionCloseAllDocuments"));
        actionOpenProject = new QAction(MainWindow);
        actionOpenProject->setObjectName(QString::fromUtf8("actionOpenProject"));
        actionCloseProject = new QAction(MainWindow);
        actionCloseProject->setObjectName(QString::fromUtf8("actionCloseProject"));
        actionNewProject = new QAction(MainWindow);
        actionNewProject->setObjectName(QString::fromUtf8("actionNewProject"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        gridLayout = new QGridLayout(centralWidget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(1, 0, 1, 0);
        tabWidget = new TabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setProperty("documentMode", QVariant(true));
        tabWidget->setProperty("tabsClosable", QVariant(true));

        gridLayout->addWidget(tabWidget, 0, 0, 1, 1);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1298, 23));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QString::fromUtf8("menuEdit"));
        menuCopyToClipboard = new QMenu(menuEdit);
        menuCopyToClipboard->setObjectName(QString::fromUtf8("menuCopyToClipboard"));
        menuIndent = new QMenu(menuEdit);
        menuIndent->setObjectName(QString::fromUtf8("menuIndent"));
        menuConvert_case_to = new QMenu(menuEdit);
        menuConvert_case_to->setObjectName(QString::fromUtf8("menuConvert_case_to"));
        menuLineOperations = new QMenu(menuEdit);
        menuLineOperations->setObjectName(QString::fromUtf8("menuLineOperations"));
        menuComment_Uncomment = new QMenu(menuEdit);
        menuComment_Uncomment->setObjectName(QString::fromUtf8("menuComment_Uncomment"));
        menuAutoCompletion = new QMenu(menuEdit);
        menuAutoCompletion->setObjectName(QString::fromUtf8("menuAutoCompletion"));
        menuEOLConversion = new QMenu(menuEdit);
        menuEOLConversion->setObjectName(QString::fromUtf8("menuEOLConversion"));
        menuBlankOperations = new QMenu(menuEdit);
        menuBlankOperations->setObjectName(QString::fromUtf8("menuBlankOperations"));
        menuPasteSpecial = new QMenu(menuEdit);
        menuPasteSpecial->setObjectName(QString::fromUtf8("menuPasteSpecial"));
        menuSearch = new QMenu(menuBar);
        menuSearch->setObjectName(QString::fromUtf8("menuSearch"));
        menuMarkAll = new QMenu(menuSearch);
        menuMarkAll->setObjectName(QString::fromUtf8("menuMarkAll"));
        menuUnmarkAll = new QMenu(menuSearch);
        menuUnmarkAll->setObjectName(QString::fromUtf8("menuUnmarkAll"));
        menuJumpUp = new QMenu(menuSearch);
        menuJumpUp->setObjectName(QString::fromUtf8("menuJumpUp"));
        menuJumpDown = new QMenu(menuSearch);
        menuJumpDown->setObjectName(QString::fromUtf8("menuJumpDown"));
        menuBookmark = new QMenu(menuSearch);
        menuBookmark->setObjectName(QString::fromUtf8("menuBookmark"));
        menuExtension = new QMenu(menuBar);
        menuExtension->setObjectName(QString::fromUtf8("menuExtension"));
        menuMacros = new QMenu(menuExtension);
        menuMacros->setObjectName(QString::fromUtf8("menuMacros"));
        menuExtensionEditor = new QMenu(menuExtension);
        menuExtensionEditor->setObjectName(QString::fromUtf8("menuExtensionEditor"));
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menuShowSymbol = new QMenu(menuView);
        menuShowSymbol->setObjectName(QString::fromUtf8("menuShowSymbol"));
        menuZoom = new QMenu(menuView);
        menuZoom->setObjectName(QString::fromUtf8("menuZoom"));
        menuEn_coding = new QMenu(menuBar);
        menuEn_coding->setObjectName(QString::fromUtf8("menuEn_coding"));
        menuTool = new QMenu(menuBar);
        menuTool->setObjectName(QString::fromUtf8("menuTool"));
        menuPlugins = new QMenu(menuBar);
        menuPlugins->setObjectName(QString::fromUtf8("menuPlugins"));
        menuWindow = new QMenu(menuBar);
        menuWindow->setObjectName(QString::fromUtf8("menuWindow"));
        menuProject = new QMenu(menuBar);
        menuProject->setObjectName(QString::fromUtf8("menuProject"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuSearch->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuEn_coding->menuAction());
        menuBar->addAction(menuProject->menuAction());
        menuBar->addAction(menuTool->menuAction());
        menuBar->addAction(menuExtension->menuAction());
        menuBar->addAction(menuPlugins->menuAction());
        menuBar->addAction(menuWindow->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionNewFile);
        menuFile->addAction(actionOpenFile);
        menuFile->addAction(actionReloadFromDisk);
        menuFile->addAction(actionSaveFile);
        menuFile->addAction(actionSaveAs);
        menuFile->addAction(actionSaveAll);
        menuFile->addAction(actionClose);
        menuFile->addAction(actionCloseAll);
        menuFile->addAction(actionCloseAllButActiveDocument);
        menuFile->addSeparator();
        menuFile->addAction(actionPrint);
        menuFile->addAction(actionPrintNow);
        menuFile->addSeparator();
        menuFile->addAction(actionRecentFiles);
        menuFile->addAction(actionOpenAllRecentFiles);
        menuFile->addAction(actionEmptyRecentFilesList);
        menuFile->addSeparator();
        menuFile->addAction(actionExitApp);
        menuHelp->addAction(actionHelpContent);
        menuHelp->addSeparator();
        menuHelp->addAction(actionDForDSoftwareHome);
        menuHelp->addAction(actionAinesmileProductPage);
        menuHelp->addSeparator();
        menuHelp->addAction(actionRegistration);
        menuHelp->addAction(actionAboutApp);
        menuEdit->addAction(actionUndo);
        menuEdit->addAction(actionRedo);
        menuEdit->addSeparator();
        menuEdit->addAction(actionCut);
        menuEdit->addAction(actionCopy);
        menuEdit->addAction(actionPaste);
        menuEdit->addAction(actionDelete);
        menuEdit->addAction(actionSelectAll);
        menuEdit->addSeparator();
        menuEdit->addAction(menuCopyToClipboard->menuAction());
        menuEdit->addAction(menuIndent->menuAction());
        menuEdit->addAction(menuConvert_case_to->menuAction());
        menuEdit->addAction(menuLineOperations->menuAction());
        menuEdit->addAction(menuComment_Uncomment->menuAction());
        menuEdit->addAction(menuAutoCompletion->menuAction());
        menuEdit->addAction(menuEOLConversion->menuAction());
        menuEdit->addAction(menuBlankOperations->menuAction());
        menuEdit->addAction(menuPasteSpecial->menuAction());
        menuEdit->addSeparator();
        menuEdit->addAction(actionColumnMode);
        menuEdit->addAction(actionColumnEditor);
        menuEdit->addAction(actionCharacterPanel);
        menuEdit->addAction(actionClipboardHistory);
        menuEdit->addSeparator();
        menuEdit->addAction(actionSetReadOnly);
        menuEdit->addAction(actionClearReadOnlyFlag);
        menuCopyToClipboard->addAction(actionCurrentFullFilePathToClipboard);
        menuCopyToClipboard->addAction(actionCurrentFileNameToClipboard);
        menuCopyToClipboard->addAction(actionCurrentDirectoryPathToClipboard);
        menuIndent->addAction(actionIncreaseLineIndent);
        menuIndent->addAction(actionDecreaseLineIndent);
        menuConvert_case_to->addAction(actionUppercase);
        menuConvert_case_to->addAction(actionLowercase);
        menuLineOperations->addAction(actionDuplicateCurrentLine);
        menuLineOperations->addAction(actionSplitLines);
        menuLineOperations->addAction(actionJoinLines);
        menuLineOperations->addAction(actionMoveUpCurrentLine);
        menuLineOperations->addAction(actionMoveDownCurrentLine);
        menuComment_Uncomment->addAction(actionToggleBlockComment);
        menuComment_Uncomment->addAction(actionBlockComment);
        menuComment_Uncomment->addAction(actionBlockUncomment);
        menuComment_Uncomment->addAction(actionStreamComment);
        menuAutoCompletion->addAction(actionFunctionCompletion);
        menuAutoCompletion->addAction(actionWordCompletion);
        menuAutoCompletion->addAction(actionFunctionParametersHint);
        menuEOLConversion->addAction(actionWindowsFormat);
        menuEOLConversion->addAction(actionUNIXFormat);
        menuEOLConversion->addAction(actionMacFormat);
        menuBlankOperations->addAction(actionTrimTrailingSpace);
        menuBlankOperations->addAction(actionTrimLeadingSpace);
        menuBlankOperations->addAction(actionTrimLeadingAndTrailingSpace);
        menuBlankOperations->addAction(actionEOLToSpace);
        menuBlankOperations->addAction(actionRemoveUnnecessaryBlankAndEOL);
        menuBlankOperations->addSeparator();
        menuBlankOperations->addAction(actionTABToSpace);
        menuBlankOperations->addAction(actionSpaceToTAB);
        menuPasteSpecial->addAction(actionPasteHTMLContent);
        menuPasteSpecial->addAction(actionPasteRTFContent);
        menuPasteSpecial->addSeparator();
        menuPasteSpecial->addAction(actionCopyBinaryContent);
        menuPasteSpecial->addAction(actionCutBinaryContent);
        menuPasteSpecial->addAction(actionPasteBinaryContent);
        menuSearch->addAction(actionFind);
        menuSearch->addAction(actionFindInFiles);
        menuSearch->addAction(actionFindNext);
        menuSearch->addAction(actionFindPrevious);
        menuSearch->addAction(actionSelectAndFindNext);
        menuSearch->addAction(actionSelectAndFindPrevious);
        menuSearch->addAction(actionFindVolatieNext);
        menuSearch->addAction(actionFindVolatiePrevious);
        menuSearch->addAction(actionReplace);
        menuSearch->addAction(actionIncrementalSearch);
        menuSearch->addAction(actionSearchResultsWindow);
        menuSearch->addAction(actionNextSearchResult);
        menuSearch->addAction(actionPreviousSearchResult);
        menuSearch->addAction(actionGoTo);
        menuSearch->addAction(actionGoToMatchingBrace);
        menuSearch->addSeparator();
        menuSearch->addAction(menuMarkAll->menuAction());
        menuSearch->addAction(menuUnmarkAll->menuAction());
        menuSearch->addAction(menuJumpUp->menuAction());
        menuSearch->addAction(menuJumpDown->menuAction());
        menuSearch->addSeparator();
        menuSearch->addAction(menuBookmark->menuAction());
        menuSearch->addSeparator();
        menuSearch->addAction(actionFindCharactersInRange);
        menuMarkAll->addAction(actionUsing1stStyle);
        menuMarkAll->addAction(actionUsing2ndStyle);
        menuMarkAll->addAction(actionUsing3rdStyle);
        menuMarkAll->addAction(actionUsing4thStyle);
        menuMarkAll->addAction(actionUsing5thStyle);
        menuUnmarkAll->addAction(actionClear1stStyle);
        menuUnmarkAll->addAction(actionClear2ndStyle);
        menuUnmarkAll->addAction(actionClear3rdStyle);
        menuUnmarkAll->addAction(actionClear4thStyle);
        menuUnmarkAll->addAction(actionClear5thStyle);
        menuUnmarkAll->addAction(actionClearAllStyle);
        menuJumpUp->addAction(actionJumpUp1stStyle);
        menuJumpUp->addAction(actionJumpUp2ndStyle);
        menuJumpUp->addAction(actionJumpUp3rdStyle);
        menuJumpUp->addAction(actionJumpUp4thStyle);
        menuJumpUp->addAction(actionJumpUp5thStyle);
        menuJumpUp->addAction(actionJumpUpFindStyle);
        menuJumpDown->addAction(actionJumpDown1stStyle);
        menuJumpDown->addAction(actionJumpDown2ndStyle);
        menuJumpDown->addAction(actionJumpDown3rdStyle);
        menuJumpDown->addAction(actionJumpDown4thStyle);
        menuJumpDown->addAction(actionJumpDown5thStyle);
        menuJumpDown->addAction(actionJumpDownFindStyle);
        menuBookmark->addAction(actionToggleBookmark);
        menuBookmark->addAction(actionNextBookmark);
        menuBookmark->addAction(actionPreviousBookmark);
        menuBookmark->addAction(actionClearAllBookmarks);
        menuBookmark->addAction(actionCutBookmarkedLines);
        menuBookmark->addAction(actionCopyBookmarkedLines);
        menuBookmark->addAction(actionPasteToReplaceBookmarkedLines);
        menuBookmark->addAction(actionRemoveBookmarkedLines);
        menuBookmark->addAction(actionRemoveUnmarkedLines);
        menuBookmark->addAction(actionInverseBookmark);
        menuExtension->addAction(actionSelectExtensionItem);
        menuExtension->addSeparator();
        menuExtension->addAction(menuMacros->menuAction());
        menuExtension->addAction(menuExtensionEditor->menuAction());
        menuMacros->addAction(actionStartRecording);
        menuMacros->addAction(actionAbortRecording);
        menuMacros->addSeparator();
        menuMacros->addAction(actionSaveLastRecording);
        menuMacros->addAction(actionReplayLastRecording);
        menuExtensionEditor->addAction(actionShowExtensionEditor);
        menuExtensionEditor->addSeparator();
        menuExtensionEditor->addAction(actionEditCommands);
        menuExtensionEditor->addAction(actionEditSnippets);
        menuExtensionEditor->addSeparator();
        menuExtensionEditor->addAction(actionReloadExtensions);
        menuView->addAction(actionAlwaysOnTop);
        menuView->addAction(actionToggleFullScreenMode);
        menuView->addAction(actionPostIt);
        menuView->addSeparator();
        menuView->addAction(menuShowSymbol->menuAction());
        menuView->addAction(menuZoom->menuAction());
        menuView->addAction(actionWordWrap);
        menuView->addAction(actionFocusOnAnotherView);
        menuView->addAction(actionHideLines);
        menuView->addAction(actionUserDefinedDialog);
        menuView->addSeparator();
        menuView->addAction(actionFoldAll);
        menuView->addAction(actionUnfoldAll);
        menuView->addAction(actionCollapseCurrentLevel);
        menuView->addAction(actionUncollapseCurrentLevel);
        menuView->addAction(actionCollapseLevel);
        menuView->addAction(actionUnCollapseLevel);
        menuView->addSeparator();
        menuView->addAction(actionSummary);
        menuView->addSeparator();
        menuView->addAction(actionSynchronizeVerticalScrolling);
        menuView->addAction(actionSynchronizeHorizontalScrolling);
        menuView->addSeparator();
        menuView->addAction(actionTextDirectionRTL);
        menuView->addAction(actionTextDirectionLTR);
        menuShowSymbol->addAction(actionShowWhiteSpaceAndTAB);
        menuShowSymbol->addAction(actionShowEndOfLine);
        menuShowSymbol->addAction(actionShowAllCharacters);
        menuShowSymbol->addSeparator();
        menuShowSymbol->addAction(actionShowIndentGuide);
        menuShowSymbol->addAction(actionShowWrapSymbol);
        menuZoom->addAction(actionZoomIn);
        menuZoom->addAction(actionZoomOut);
        menuZoom->addAction(actionRestoreDefaultZoom);
        menuEn_coding->addAction(actionEncodeInANSI);
        menuEn_coding->addAction(actionEncodeInUTF8WithoutBOM);
        menuEn_coding->addAction(actionEncodeInUTF8);
        menuEn_coding->addAction(actionEncodeInUCS2BigEndian);
        menuEn_coding->addAction(actionEncodeInUCS2LittleEndian);
        menuEn_coding->addAction(actionCharacterSets);
        menuEn_coding->addSeparator();
        menuEn_coding->addAction(actionConvertToANSI);
        menuEn_coding->addAction(actionConvertToUTF8WithoutBOM);
        menuEn_coding->addAction(actionConvertToUTF8);
        menuEn_coding->addAction(actionConvertToUCS2BigEndian);
        menuEn_coding->addAction(actionConvertToUCS2LittleEndian);
        menuTool->addAction(actionPreferences);
        menuTool->addSeparator();
        menuTool->addAction(actionExternal_Tools);
        menuTool->addAction(actionLanguage);
        menuPlugins->addAction(actionPluginManager);
        menuWindow->addAction(actionWindowsList);
        menuWindow->addAction(actionCloseAllDocuments);
        menuWindow->addSeparator();
        menuProject->addAction(actionNewProject);
        menuProject->addAction(actionOpenProject);
        menuProject->addAction(actionCloseProject);
        mainToolBar->addAction(actionNewFile);
        mainToolBar->addAction(actionOpenFile);
        mainToolBar->addAction(actionSaveFile);
        mainToolBar->addAction(actionSaveAll);
        mainToolBar->addAction(actionPrint);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionUndo);
        mainToolBar->addAction(actionRedo);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionCut);
        mainToolBar->addAction(actionCopy);
        mainToolBar->addAction(actionPaste);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionFind);
        mainToolBar->addAction(actionReplace);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Ainesmile", 0, QApplication::UnicodeUTF8));
        actionOpenFile->setText(QApplication::translate("MainWindow", "&Open...", 0, QApplication::UnicodeUTF8));
        actionOpenFile->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0, QApplication::UnicodeUTF8));
        actionSaveFile->setText(QApplication::translate("MainWindow", "&Save", 0, QApplication::UnicodeUTF8));
        actionSaveFile->setShortcut(QApplication::translate("MainWindow", "Ctrl+S", 0, QApplication::UnicodeUTF8));
        actionSaveAs->setText(QApplication::translate("MainWindow", "Save &As...", 0, QApplication::UnicodeUTF8));
        actionExitApp->setText(QApplication::translate("MainWindow", "E&xit", 0, QApplication::UnicodeUTF8));
        actionExitApp->setShortcut(QApplication::translate("MainWindow", "Ctrl+Q", 0, QApplication::UnicodeUTF8));
        actionHelpContent->setText(QApplication::translate("MainWindow", "&Content", 0, QApplication::UnicodeUTF8));
        actionHelpContent->setShortcut(QApplication::translate("MainWindow", "F1", 0, QApplication::UnicodeUTF8));
        actionAboutApp->setText(QApplication::translate("MainWindow", "&About", 0, QApplication::UnicodeUTF8));
        actionNewFile->setText(QApplication::translate("MainWindow", "&New", 0, QApplication::UnicodeUTF8));
        actionNewFile->setShortcut(QApplication::translate("MainWindow", "Ctrl+N", 0, QApplication::UnicodeUTF8));
        actionReloadFromDisk->setText(QApplication::translate("MainWindow", "Reload from Disk", 0, QApplication::UnicodeUTF8));
        actionSaveAll->setText(QApplication::translate("MainWindow", "Save All", 0, QApplication::UnicodeUTF8));
        actionClose->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
        actionClose->setShortcut(QApplication::translate("MainWindow", "Ctrl+W", 0, QApplication::UnicodeUTF8));
        actionCloseAll->setText(QApplication::translate("MainWindow", "Close All", 0, QApplication::UnicodeUTF8));
        actionCloseAllButActiveDocument->setText(QApplication::translate("MainWindow", "Close All but Active Document", 0, QApplication::UnicodeUTF8));
        actionPrint->setText(QApplication::translate("MainWindow", "Print...", 0, QApplication::UnicodeUTF8));
        actionPrint->setShortcut(QApplication::translate("MainWindow", "Ctrl+P", 0, QApplication::UnicodeUTF8));
        actionPrintNow->setText(QApplication::translate("MainWindow", "Print Now", 0, QApplication::UnicodeUTF8));
        actionOpenAllRecentFiles->setText(QApplication::translate("MainWindow", "Open All Recent Files", 0, QApplication::UnicodeUTF8));
        actionEmptyRecentFilesList->setText(QApplication::translate("MainWindow", "Empty Recent Files List", 0, QApplication::UnicodeUTF8));
        actionRecentFiles->setText(QApplication::translate("MainWindow", "Recent Files", 0, QApplication::UnicodeUTF8));
        actionUndo->setText(QApplication::translate("MainWindow", "&Undo", 0, QApplication::UnicodeUTF8));
        actionUndo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Z", 0, QApplication::UnicodeUTF8));
        actionRedo->setText(QApplication::translate("MainWindow", "&Redo", 0, QApplication::UnicodeUTF8));
        actionRedo->setShortcut(QApplication::translate("MainWindow", "Ctrl+Y", 0, QApplication::UnicodeUTF8));
        actionCut->setText(QApplication::translate("MainWindow", "Cu&t", 0, QApplication::UnicodeUTF8));
        actionCut->setShortcut(QApplication::translate("MainWindow", "Ctrl+X", 0, QApplication::UnicodeUTF8));
        actionCopy->setText(QApplication::translate("MainWindow", "&Copy", 0, QApplication::UnicodeUTF8));
        actionCopy->setShortcut(QApplication::translate("MainWindow", "Ctrl+C", 0, QApplication::UnicodeUTF8));
        actionPaste->setText(QApplication::translate("MainWindow", "&Paste", 0, QApplication::UnicodeUTF8));
        actionPaste->setShortcut(QApplication::translate("MainWindow", "Ctrl+V", 0, QApplication::UnicodeUTF8));
        actionDelete->setText(QApplication::translate("MainWindow", "&Delete", 0, QApplication::UnicodeUTF8));
        actionDelete->setShortcut(QApplication::translate("MainWindow", "Del", 0, QApplication::UnicodeUTF8));
        actionSelectAll->setText(QApplication::translate("MainWindow", "Select &All", 0, QApplication::UnicodeUTF8));
        actionSelectAll->setShortcut(QApplication::translate("MainWindow", "Ctrl+A", 0, QApplication::UnicodeUTF8));
        actionColumnMode->setText(QApplication::translate("MainWindow", "Column Mode...", 0, QApplication::UnicodeUTF8));
        actionColumnEditor->setText(QApplication::translate("MainWindow", "Column Editor...", 0, QApplication::UnicodeUTF8));
        actionColumnEditor->setShortcut(QApplication::translate("MainWindow", "Alt+C", 0, QApplication::UnicodeUTF8));
        actionCharacterPanel->setText(QApplication::translate("MainWindow", "Character Panel", 0, QApplication::UnicodeUTF8));
        actionClipboardHistory->setText(QApplication::translate("MainWindow", "Clipboard History", 0, QApplication::UnicodeUTF8));
        actionSetReadOnly->setText(QApplication::translate("MainWindow", "Set Read-Only", 0, QApplication::UnicodeUTF8));
        actionClearReadOnlyFlag->setText(QApplication::translate("MainWindow", "Clear Read-Only Flag", 0, QApplication::UnicodeUTF8));
        actionCurrentFullFilePathToClipboard->setText(QApplication::translate("MainWindow", "Current Full File Path to Clipboard", 0, QApplication::UnicodeUTF8));
        actionCurrentFileNameToClipboard->setText(QApplication::translate("MainWindow", "Current File Name to Clipboard", 0, QApplication::UnicodeUTF8));
        actionCurrentDirectoryPathToClipboard->setText(QApplication::translate("MainWindow", "Current Directory Path to Clipboard", 0, QApplication::UnicodeUTF8));
        actionIncreaseLineIndent->setText(QApplication::translate("MainWindow", "Increase Line Indent", 0, QApplication::UnicodeUTF8));
        actionDecreaseLineIndent->setText(QApplication::translate("MainWindow", "Decrease Line Indent", 0, QApplication::UnicodeUTF8));
        actionUppercase->setText(QApplication::translate("MainWindow", "UPPERCASE", 0, QApplication::UnicodeUTF8));
        actionLowercase->setText(QApplication::translate("MainWindow", "lowercase", 0, QApplication::UnicodeUTF8));
        actionDuplicateCurrentLine->setText(QApplication::translate("MainWindow", "Duplicate Current Line", 0, QApplication::UnicodeUTF8));
        actionSplitLines->setText(QApplication::translate("MainWindow", "Split Lines", 0, QApplication::UnicodeUTF8));
        actionJoinLines->setText(QApplication::translate("MainWindow", "Join Lines", 0, QApplication::UnicodeUTF8));
        actionMoveUpCurrentLine->setText(QApplication::translate("MainWindow", "Move Up Current Line", 0, QApplication::UnicodeUTF8));
        actionMoveDownCurrentLine->setText(QApplication::translate("MainWindow", "Move Down Current Line", 0, QApplication::UnicodeUTF8));
        actionToggleBlockComment->setText(QApplication::translate("MainWindow", "Toggle Block Comment", 0, QApplication::UnicodeUTF8));
        actionBlockComment->setText(QApplication::translate("MainWindow", "Block Comment", 0, QApplication::UnicodeUTF8));
        actionBlockUncomment->setText(QApplication::translate("MainWindow", "Block Uncomment", 0, QApplication::UnicodeUTF8));
        actionStreamComment->setText(QApplication::translate("MainWindow", "Stream Comment", 0, QApplication::UnicodeUTF8));
        actionFunctionCompletion->setText(QApplication::translate("MainWindow", "Function Completion", 0, QApplication::UnicodeUTF8));
        actionWordCompletion->setText(QApplication::translate("MainWindow", "Word Completion", 0, QApplication::UnicodeUTF8));
        actionFunctionParametersHint->setText(QApplication::translate("MainWindow", "Function Parameters Hint", 0, QApplication::UnicodeUTF8));
        actionWindowsFormat->setText(QApplication::translate("MainWindow", "Windows Format", 0, QApplication::UnicodeUTF8));
        actionUNIXFormat->setText(QApplication::translate("MainWindow", "UNIX Format", 0, QApplication::UnicodeUTF8));
        actionMacFormat->setText(QApplication::translate("MainWindow", "Mac Format", 0, QApplication::UnicodeUTF8));
        actionTrimTrailingSpace->setText(QApplication::translate("MainWindow", "Trim Trailing Space", 0, QApplication::UnicodeUTF8));
        actionTrimLeadingSpace->setText(QApplication::translate("MainWindow", "Trim Leading Space", 0, QApplication::UnicodeUTF8));
        actionTrimLeadingAndTrailingSpace->setText(QApplication::translate("MainWindow", "Trim Leading and Trailing Space", 0, QApplication::UnicodeUTF8));
        actionEOLToSpace->setText(QApplication::translate("MainWindow", "EOL to Space", 0, QApplication::UnicodeUTF8));
        actionRemoveUnnecessaryBlankAndEOL->setText(QApplication::translate("MainWindow", "Remove Unnecessary Blank and EOL", 0, QApplication::UnicodeUTF8));
        actionTABToSpace->setText(QApplication::translate("MainWindow", "TAB to Space", 0, QApplication::UnicodeUTF8));
        actionSpaceToTAB->setText(QApplication::translate("MainWindow", "Space to TAB", 0, QApplication::UnicodeUTF8));
        actionPasteHTMLContent->setText(QApplication::translate("MainWindow", "Paste HTML Content", 0, QApplication::UnicodeUTF8));
        actionPasteRTFContent->setText(QApplication::translate("MainWindow", "Paste RTF Content", 0, QApplication::UnicodeUTF8));
        actionCopyBinaryContent->setText(QApplication::translate("MainWindow", "Copy Binary Content", 0, QApplication::UnicodeUTF8));
        actionCutBinaryContent->setText(QApplication::translate("MainWindow", "Cut Binary Content", 0, QApplication::UnicodeUTF8));
        actionPasteBinaryContent->setText(QApplication::translate("MainWindow", "Paste Binary Content", 0, QApplication::UnicodeUTF8));
        actionFind->setText(QApplication::translate("MainWindow", "&Find...", 0, QApplication::UnicodeUTF8));
        actionFind->setShortcut(QApplication::translate("MainWindow", "Ctrl+F", 0, QApplication::UnicodeUTF8));
        actionFindInFiles->setText(QApplication::translate("MainWindow", "Find in Files...", 0, QApplication::UnicodeUTF8));
        actionFindInFiles->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+F", 0, QApplication::UnicodeUTF8));
        actionFindNext->setText(QApplication::translate("MainWindow", "Find &Next", 0, QApplication::UnicodeUTF8));
        actionFindNext->setShortcut(QApplication::translate("MainWindow", "F3", 0, QApplication::UnicodeUTF8));
        actionFindPrevious->setText(QApplication::translate("MainWindow", "Find &Previous", 0, QApplication::UnicodeUTF8));
        actionFindPrevious->setShortcut(QApplication::translate("MainWindow", "Shift+F3", 0, QApplication::UnicodeUTF8));
        actionSelectAndFindNext->setText(QApplication::translate("MainWindow", "Select and Find Next", 0, QApplication::UnicodeUTF8));
        actionSelectAndFindNext->setShortcut(QApplication::translate("MainWindow", "Ctrl+F3", 0, QApplication::UnicodeUTF8));
        actionSelectAndFindPrevious->setText(QApplication::translate("MainWindow", "Select and Find Previous", 0, QApplication::UnicodeUTF8));
        actionSelectAndFindPrevious->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+F3", 0, QApplication::UnicodeUTF8));
        actionFindVolatieNext->setText(QApplication::translate("MainWindow", "Find (Volatie) Next", 0, QApplication::UnicodeUTF8));
        actionFindVolatieNext->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+F3", 0, QApplication::UnicodeUTF8));
        actionFindVolatiePrevious->setText(QApplication::translate("MainWindow", "Find (Volatie) Previous", 0, QApplication::UnicodeUTF8));
        actionFindVolatiePrevious->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+Shift+F3", 0, QApplication::UnicodeUTF8));
        actionReplace->setText(QApplication::translate("MainWindow", "&Replace...", 0, QApplication::UnicodeUTF8));
        actionIncrementalSearch->setText(QApplication::translate("MainWindow", "Incremental Search", 0, QApplication::UnicodeUTF8));
        actionIncrementalSearch->setShortcut(QApplication::translate("MainWindow", "Ctrl+Alt+I", 0, QApplication::UnicodeUTF8));
        actionSearchResultsWindow->setText(QApplication::translate("MainWindow", "Search Results Window", 0, QApplication::UnicodeUTF8));
        actionSearchResultsWindow->setShortcut(QApplication::translate("MainWindow", "F7", 0, QApplication::UnicodeUTF8));
        actionNextSearchResult->setText(QApplication::translate("MainWindow", "Next Search Result", 0, QApplication::UnicodeUTF8));
        actionNextSearchResult->setShortcut(QApplication::translate("MainWindow", "F4", 0, QApplication::UnicodeUTF8));
        actionPreviousSearchResult->setText(QApplication::translate("MainWindow", "Previous Search Result", 0, QApplication::UnicodeUTF8));
        actionPreviousSearchResult->setShortcut(QApplication::translate("MainWindow", "Shift+F4", 0, QApplication::UnicodeUTF8));
        actionGoTo->setText(QApplication::translate("MainWindow", "Go to...", 0, QApplication::UnicodeUTF8));
        actionGoTo->setShortcut(QApplication::translate("MainWindow", "Ctrl+G", 0, QApplication::UnicodeUTF8));
        actionGoToMatchingBrace->setText(QApplication::translate("MainWindow", "Go to Matching Brace", 0, QApplication::UnicodeUTF8));
        actionGoToMatchingBrace->setShortcut(QApplication::translate("MainWindow", "Ctrl+B", 0, QApplication::UnicodeUTF8));
        actionFindCharactersInRange->setText(QApplication::translate("MainWindow", "Find characters in range...", 0, QApplication::UnicodeUTF8));
        actionUsing1stStyle->setText(QApplication::translate("MainWindow", "Using 1st Style", 0, QApplication::UnicodeUTF8));
        actionUsing2ndStyle->setText(QApplication::translate("MainWindow", "Using 2nd Style", 0, QApplication::UnicodeUTF8));
        actionUsing3rdStyle->setText(QApplication::translate("MainWindow", "Using 3rd Style", 0, QApplication::UnicodeUTF8));
        actionUsing4thStyle->setText(QApplication::translate("MainWindow", "Using 4th Style", 0, QApplication::UnicodeUTF8));
        actionUsing5thStyle->setText(QApplication::translate("MainWindow", "Using 5th Style", 0, QApplication::UnicodeUTF8));
        actionClear1stStyle->setText(QApplication::translate("MainWindow", "Clear 1st Style", 0, QApplication::UnicodeUTF8));
        actionClear2ndStyle->setText(QApplication::translate("MainWindow", "Clear 2nd Style", 0, QApplication::UnicodeUTF8));
        actionClear3rdStyle->setText(QApplication::translate("MainWindow", "Clear 3rd Style", 0, QApplication::UnicodeUTF8));
        actionClear4thStyle->setText(QApplication::translate("MainWindow", "Clear 4th Style", 0, QApplication::UnicodeUTF8));
        actionClear5thStyle->setText(QApplication::translate("MainWindow", "Clear 5th Style", 0, QApplication::UnicodeUTF8));
        actionClearAllStyle->setText(QApplication::translate("MainWindow", "Clear All Style", 0, QApplication::UnicodeUTF8));
        actionJumpUp1stStyle->setText(QApplication::translate("MainWindow", "1st Style", 0, QApplication::UnicodeUTF8));
        actionJumpUp1stStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+1", 0, QApplication::UnicodeUTF8));
        actionJumpUp2ndStyle->setText(QApplication::translate("MainWindow", "2nd Style", 0, QApplication::UnicodeUTF8));
        actionJumpUp2ndStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+2", 0, QApplication::UnicodeUTF8));
        actionJumpUp3rdStyle->setText(QApplication::translate("MainWindow", "3rd Style", 0, QApplication::UnicodeUTF8));
        actionJumpUp4thStyle->setText(QApplication::translate("MainWindow", "4th Style", 0, QApplication::UnicodeUTF8));
        actionJumpUp5thStyle->setText(QApplication::translate("MainWindow", "5th Style", 0, QApplication::UnicodeUTF8));
        actionJumpUp5thStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+5", 0, QApplication::UnicodeUTF8));
        actionJumpUpFindStyle->setText(QApplication::translate("MainWindow", "Find Style", 0, QApplication::UnicodeUTF8));
        actionJumpUpFindStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+Shift+0", 0, QApplication::UnicodeUTF8));
        actionJumpDown1stStyle->setText(QApplication::translate("MainWindow", "1st Style", 0, QApplication::UnicodeUTF8));
        actionJumpDown1stStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+1", 0, QApplication::UnicodeUTF8));
        actionJumpDown2ndStyle->setText(QApplication::translate("MainWindow", "2nd Style", 0, QApplication::UnicodeUTF8));
        actionJumpDown2ndStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+2", 0, QApplication::UnicodeUTF8));
        actionJumpDown3rdStyle->setText(QApplication::translate("MainWindow", "3rd Style", 0, QApplication::UnicodeUTF8));
        actionJumpDown3rdStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+3", 0, QApplication::UnicodeUTF8));
        actionJumpDown4thStyle->setText(QApplication::translate("MainWindow", "4th Style", 0, QApplication::UnicodeUTF8));
        actionJumpDown4thStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+4", 0, QApplication::UnicodeUTF8));
        actionJumpDown5thStyle->setText(QApplication::translate("MainWindow", "5th Style", 0, QApplication::UnicodeUTF8));
        actionJumpDown5thStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+5", 0, QApplication::UnicodeUTF8));
        actionJumpDownFindStyle->setText(QApplication::translate("MainWindow", "Find Style", 0, QApplication::UnicodeUTF8));
        actionJumpDownFindStyle->setShortcut(QApplication::translate("MainWindow", "Ctrl+0", 0, QApplication::UnicodeUTF8));
        actionToggleBookmark->setText(QApplication::translate("MainWindow", "Toggle Bookmark", 0, QApplication::UnicodeUTF8));
        actionToggleBookmark->setShortcut(QApplication::translate("MainWindow", "Ctrl+F2", 0, QApplication::UnicodeUTF8));
        actionNextBookmark->setText(QApplication::translate("MainWindow", "Next Bookmark", 0, QApplication::UnicodeUTF8));
        actionNextBookmark->setShortcut(QApplication::translate("MainWindow", "F2", 0, QApplication::UnicodeUTF8));
        actionPreviousBookmark->setText(QApplication::translate("MainWindow", "Previous Bookmark", 0, QApplication::UnicodeUTF8));
        actionPreviousBookmark->setShortcut(QApplication::translate("MainWindow", "Shift+F2", 0, QApplication::UnicodeUTF8));
        actionClearAllBookmarks->setText(QApplication::translate("MainWindow", "Clear All Bookmarks", 0, QApplication::UnicodeUTF8));
        actionCutBookmarkedLines->setText(QApplication::translate("MainWindow", "Cut Bookmarked Lines", 0, QApplication::UnicodeUTF8));
        actionCopyBookmarkedLines->setText(QApplication::translate("MainWindow", "Copy Bookmarked Lines", 0, QApplication::UnicodeUTF8));
        actionPasteToReplaceBookmarkedLines->setText(QApplication::translate("MainWindow", "Paste to (Replace) Bookmarked Lines", 0, QApplication::UnicodeUTF8));
        actionRemoveBookmarkedLines->setText(QApplication::translate("MainWindow", "Remove Bookmarked Lines", 0, QApplication::UnicodeUTF8));
        actionRemoveUnmarkedLines->setText(QApplication::translate("MainWindow", "Remove Unmarked Lines", 0, QApplication::UnicodeUTF8));
        actionInverseBookmark->setText(QApplication::translate("MainWindow", "Inverse Bookmark", 0, QApplication::UnicodeUTF8));
        actionRegistration->setText(QApplication::translate("MainWindow", "Registration...", 0, QApplication::UnicodeUTF8));
        actionSelectExtensionItem->setText(QApplication::translate("MainWindow", "Select Extension Item...", 0, QApplication::UnicodeUTF8));
        actionStartRecording->setText(QApplication::translate("MainWindow", "Start Recording...", 0, QApplication::UnicodeUTF8));
        actionAbortRecording->setText(QApplication::translate("MainWindow", "Abort Recording", 0, QApplication::UnicodeUTF8));
        actionSaveLastRecording->setText(QApplication::translate("MainWindow", "Save Last Recording", 0, QApplication::UnicodeUTF8));
        actionReplayLastRecording->setText(QApplication::translate("MainWindow", "Replay Last Recording", 0, QApplication::UnicodeUTF8));
        actionShowExtensionEditor->setText(QApplication::translate("MainWindow", "Show Extension Editor", 0, QApplication::UnicodeUTF8));
        actionEditCommands->setText(QApplication::translate("MainWindow", "Edit Commands...", 0, QApplication::UnicodeUTF8));
        actionEditSnippets->setText(QApplication::translate("MainWindow", "Edit Snippets...", 0, QApplication::UnicodeUTF8));
        actionReloadExtensions->setText(QApplication::translate("MainWindow", "Reload Extensions", 0, QApplication::UnicodeUTF8));
        action_Plugins->setText(QApplication::translate("MainWindow", "&Plugins", 0, QApplication::UnicodeUTF8));
        actionDForDSoftwareHome->setText(QApplication::translate("MainWindow", "DForD Software Home", 0, QApplication::UnicodeUTF8));
        actionAinesmileProductPage->setText(QApplication::translate("MainWindow", "Ainesmile Product Page", 0, QApplication::UnicodeUTF8));
        actionAlwaysOnTop->setText(QApplication::translate("MainWindow", "Always on &Top", 0, QApplication::UnicodeUTF8));
        actionToggleFullScreenMode->setText(QApplication::translate("MainWindow", "Toggle Full Screen Mode", 0, QApplication::UnicodeUTF8));
        actionPostIt->setText(QApplication::translate("MainWindow", "Post-It", 0, QApplication::UnicodeUTF8));
        actionMove_Clone_Current_Document->setText(QApplication::translate("MainWindow", "Move/Clone Current Document", 0, QApplication::UnicodeUTF8));
        actionWordWrap->setText(QApplication::translate("MainWindow", "Word Wrap", 0, QApplication::UnicodeUTF8));
        actionFocusOnAnotherView->setText(QApplication::translate("MainWindow", "Focus on Another View", 0, QApplication::UnicodeUTF8));
        actionHideLines->setText(QApplication::translate("MainWindow", "Hide Lines", 0, QApplication::UnicodeUTF8));
        actionUserDefinedDialog->setText(QApplication::translate("MainWindow", "User-Defined Dialog...", 0, QApplication::UnicodeUTF8));
        actionFoldAll->setText(QApplication::translate("MainWindow", "Fold All", 0, QApplication::UnicodeUTF8));
        actionUnfoldAll->setText(QApplication::translate("MainWindow", "Unfold All", 0, QApplication::UnicodeUTF8));
        actionCollapseCurrentLevel->setText(QApplication::translate("MainWindow", "Collapse Current Level", 0, QApplication::UnicodeUTF8));
        actionUncollapseCurrentLevel->setText(QApplication::translate("MainWindow", "Uncollapse Current Level", 0, QApplication::UnicodeUTF8));
        actionCollapseLevel->setText(QApplication::translate("MainWindow", "Collapse Level", 0, QApplication::UnicodeUTF8));
        actionUnCollapseLevel->setText(QApplication::translate("MainWindow", "UnCollapse Level", 0, QApplication::UnicodeUTF8));
        actionSummary->setText(QApplication::translate("MainWindow", "Summary...", 0, QApplication::UnicodeUTF8));
        actionProject->setText(QApplication::translate("MainWindow", "Project", 0, QApplication::UnicodeUTF8));
        actionSynchronizeVerticalScrolling->setText(QApplication::translate("MainWindow", "Synchronize Vertical Scrolling", 0, QApplication::UnicodeUTF8));
        actionSynchronizeHorizontalScrolling->setText(QApplication::translate("MainWindow", "Synchronize Horizontal Scrolling", 0, QApplication::UnicodeUTF8));
        actionTextDirectionRTL->setText(QApplication::translate("MainWindow", "Text Direction RTL", 0, QApplication::UnicodeUTF8));
        actionTextDirectionLTR->setText(QApplication::translate("MainWindow", "Text Direction LTR", 0, QApplication::UnicodeUTF8));
        actionEncodeInANSI->setText(QApplication::translate("MainWindow", "Encode in ANSI", 0, QApplication::UnicodeUTF8));
        actionEncodeInUTF8WithoutBOM->setText(QApplication::translate("MainWindow", "Encode in UTF-8 without BOM", 0, QApplication::UnicodeUTF8));
        actionEncodeInUTF8->setText(QApplication::translate("MainWindow", "Encode in UTF-8", 0, QApplication::UnicodeUTF8));
        actionEncodeInUCS2BigEndian->setText(QApplication::translate("MainWindow", "Encode in UCS-2 Big Endian", 0, QApplication::UnicodeUTF8));
        actionEncodeInUCS2LittleEndian->setText(QApplication::translate("MainWindow", "Encode in UCS-2 Little Endian", 0, QApplication::UnicodeUTF8));
        actionCharacterSets->setText(QApplication::translate("MainWindow", "Character sets", 0, QApplication::UnicodeUTF8));
        actionConvertToANSI->setText(QApplication::translate("MainWindow", "Convert to ANSI", 0, QApplication::UnicodeUTF8));
        actionConvertToUTF8WithoutBOM->setText(QApplication::translate("MainWindow", "Convert to UTF-8 without BOM", 0, QApplication::UnicodeUTF8));
        actionConvertToUTF8->setText(QApplication::translate("MainWindow", "Convert to UTF-8", 0, QApplication::UnicodeUTF8));
        actionConvertToUCS2BigEndian->setText(QApplication::translate("MainWindow", "Convert to UCS-2 Big Endian", 0, QApplication::UnicodeUTF8));
        actionConvertToUCS2LittleEndian->setText(QApplication::translate("MainWindow", "Convert to UCS-2 Little Endian", 0, QApplication::UnicodeUTF8));
        actionShowWhiteSpaceAndTAB->setText(QApplication::translate("MainWindow", "Show White Space and TAB", 0, QApplication::UnicodeUTF8));
        actionShowEndOfLine->setText(QApplication::translate("MainWindow", "Show End of Line", 0, QApplication::UnicodeUTF8));
        actionShowAllCharacters->setText(QApplication::translate("MainWindow", "Show All Characters", 0, QApplication::UnicodeUTF8));
        actionShowIndentGuide->setText(QApplication::translate("MainWindow", "Show Indent Guide", 0, QApplication::UnicodeUTF8));
        actionShowWrapSymbol->setText(QApplication::translate("MainWindow", "Show Wrap Symbol", 0, QApplication::UnicodeUTF8));
        actionZoomIn->setText(QApplication::translate("MainWindow", "Zoom In", 0, QApplication::UnicodeUTF8));
        actionZoomIn->setShortcut(QApplication::translate("MainWindow", "Ctrl++", 0, QApplication::UnicodeUTF8));
        actionZoomOut->setText(QApplication::translate("MainWindow", "Zoom Out", 0, QApplication::UnicodeUTF8));
        actionZoomOut->setShortcut(QApplication::translate("MainWindow", "Ctrl+-", 0, QApplication::UnicodeUTF8));
        actionRestoreDefaultZoom->setText(QApplication::translate("MainWindow", "Restore Default Zoom", 0, QApplication::UnicodeUTF8));
        actionRestoreDefaultZoom->setShortcut(QApplication::translate("MainWindow", "Ctrl+/", 0, QApplication::UnicodeUTF8));
        actionTool->setText(QApplication::translate("MainWindow", "Tool", 0, QApplication::UnicodeUTF8));
        actionPreferences->setText(QApplication::translate("MainWindow", "Preferences...", 0, QApplication::UnicodeUTF8));
        actionExternal_Tools->setText(QApplication::translate("MainWindow", "External Tools...", 0, QApplication::UnicodeUTF8));
        actionLanguage->setText(QApplication::translate("MainWindow", "Language", 0, QApplication::UnicodeUTF8));
        actionPluginManager->setText(QApplication::translate("MainWindow", "Plugin Manager...", 0, QApplication::UnicodeUTF8));
        actionWindowsList->setText(QApplication::translate("MainWindow", "Windows List...", 0, QApplication::UnicodeUTF8));
        actionCloseAllDocuments->setText(QApplication::translate("MainWindow", "Close All Documents", 0, QApplication::UnicodeUTF8));
        actionOpenProject->setText(QApplication::translate("MainWindow", "&Open Project...", 0, QApplication::UnicodeUTF8));
        actionCloseProject->setText(QApplication::translate("MainWindow", "Close Project...", 0, QApplication::UnicodeUTF8));
        actionNewProject->setText(QApplication::translate("MainWindow", "&New Project...", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("MainWindow", "&File", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("MainWindow", "&Help", 0, QApplication::UnicodeUTF8));
        menuEdit->setTitle(QApplication::translate("MainWindow", "&Edit", 0, QApplication::UnicodeUTF8));
        menuCopyToClipboard->setTitle(QApplication::translate("MainWindow", "Copy to Clipboard", 0, QApplication::UnicodeUTF8));
        menuIndent->setTitle(QApplication::translate("MainWindow", "Indent", 0, QApplication::UnicodeUTF8));
        menuConvert_case_to->setTitle(QApplication::translate("MainWindow", "Convert case to", 0, QApplication::UnicodeUTF8));
        menuLineOperations->setTitle(QApplication::translate("MainWindow", "Line Operations", 0, QApplication::UnicodeUTF8));
        menuComment_Uncomment->setTitle(QApplication::translate("MainWindow", "Comment/Uncomment", 0, QApplication::UnicodeUTF8));
        menuAutoCompletion->setTitle(QApplication::translate("MainWindow", "Auto-Completion", 0, QApplication::UnicodeUTF8));
        menuEOLConversion->setTitle(QApplication::translate("MainWindow", "EOL Conversion", 0, QApplication::UnicodeUTF8));
        menuBlankOperations->setTitle(QApplication::translate("MainWindow", "Blank Operations", 0, QApplication::UnicodeUTF8));
        menuPasteSpecial->setTitle(QApplication::translate("MainWindow", "Paste Special", 0, QApplication::UnicodeUTF8));
        menuSearch->setTitle(QApplication::translate("MainWindow", "&Search", 0, QApplication::UnicodeUTF8));
        menuMarkAll->setTitle(QApplication::translate("MainWindow", "Mark All", 0, QApplication::UnicodeUTF8));
        menuUnmarkAll->setTitle(QApplication::translate("MainWindow", "Unmark All", 0, QApplication::UnicodeUTF8));
        menuJumpUp->setTitle(QApplication::translate("MainWindow", "Jump up", 0, QApplication::UnicodeUTF8));
        menuJumpDown->setTitle(QApplication::translate("MainWindow", "Jump down", 0, QApplication::UnicodeUTF8));
        menuBookmark->setTitle(QApplication::translate("MainWindow", "Bookmark", 0, QApplication::UnicodeUTF8));
        menuExtension->setTitle(QApplication::translate("MainWindow", "E&xtension", 0, QApplication::UnicodeUTF8));
        menuMacros->setTitle(QApplication::translate("MainWindow", "Macros", 0, QApplication::UnicodeUTF8));
        menuExtensionEditor->setTitle(QApplication::translate("MainWindow", "Extension Editor", 0, QApplication::UnicodeUTF8));
        menuView->setTitle(QApplication::translate("MainWindow", "&View", 0, QApplication::UnicodeUTF8));
        menuShowSymbol->setTitle(QApplication::translate("MainWindow", "Show Symbol", 0, QApplication::UnicodeUTF8));
        menuZoom->setTitle(QApplication::translate("MainWindow", "Zoom", 0, QApplication::UnicodeUTF8));
        menuEn_coding->setTitle(QApplication::translate("MainWindow", "En&coding", 0, QApplication::UnicodeUTF8));
        menuTool->setTitle(QApplication::translate("MainWindow", "&Tool", 0, QApplication::UnicodeUTF8));
        menuPlugins->setTitle(QApplication::translate("MainWindow", "&Plugins", 0, QApplication::UnicodeUTF8));
        menuWindow->setTitle(QApplication::translate("MainWindow", "&Window", 0, QApplication::UnicodeUTF8));
        menuProject->setTitle(QApplication::translate("MainWindow", "Pro&ject", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
