name: Build ainesmile
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/f96c71db-2c6c-45d9-8c1f-0348ef5885cf/w_BaseKit_p_2023.2.0.49396_offline.exe
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/438527fc-7140-422c-a851-389f2791816b/w_HPCKit_p_2023.2.0.49441_offline.exe
  WINDOWS_CPP_COMPONENTS: intel.oneapi.win.cpp-compiler
  WINDOWS_DPCPP_COMPONENTS: intel.oneapi.win.dpcpp-compiler
  SAMPLES_TAG: 2023.2.0
  COMPILER_VERSION: 2023.2.0
  TBB_VERSION: 2021.10.0
  VS_VER: vs2022
  BOOST_URL: https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.gz
  BOOST_PKG: boost_1_83_0
      
      
jobs:
  win64-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: win64_msvc2019_64
            qt_ver: 5.15.2
            qt_modules: ""
            msvc_arch: x64
            output_dir: x86_64
          - qt_arch: win64_msvc2019_64
            qt_ver: 6.5.2
            qt_modules: "qt5compat qtimageformats"
            msvc_arch: x64
            output_dir: x86_64
    env:
      targetName: ainesmile
      
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          target: desktop
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: ${{ matrix.qt_modules }}
          cache: 'true'
          cache-key-prefix: 'install-qt-action-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}'
          aqtversion: '==3.0.1'
          
      - name: vcpkg build
        run: |
          cd C:\vcpkg
          vcpkg install boost-property-tree:x64-windows-release uchardet:x64-windows-release
          pkgs: boost-property-tree uchardet
          triplet: x64-windows-release
          token: ${{ github.token }}
        
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      
      - name: copy CMakeLists.txt
        shell: cmd
        run: |
          cd 3rdparty
          copy cmakes\CMakeLists.txt.lexilla lexilla\CMakeLists.txt
          copy cmakes\CMakeLists.txt.scintilla scintilla\CMakeLists.txt

      - name: patch
        shell: cmd
        run: |
          cd 3rdparty\lexilla
          git apply ..\lexilla.patch
          cd ..\..
      
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%PATH%;%CD%\jom
          cd 3rdparty\scintilla\qt\ScintillaEdit
          python WidgetGen.py
          cd ..\..\..\..
          mkdir build
          cd build
          curl -o ninja.zip -sSL https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
          7z x ninja.zip
          cmake -DCMAKE_MAKE_PROGRAM=ninja.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release -DVCPKG_MANIFEST_MODE=OFF ..
          cmake --build . --parallel --verbose
          mkdir bin
          copy src\ainesmile\ainesmile.exe bin\
          windeployqt bin\ainesmile.exe
          cd ..
          
      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\bin
          name: ainesmile-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ainesmile-intel-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          asset_name: ainesmile-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true 
          
  win64-clang-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: win64_msvc2019_64
            qt_ver: 5.15.2
            qt_modules: ""
            msvc_arch: x64
            output_dir: x86_64
          - qt_arch: win64_msvc2019_64
            qt_ver: 6.5.2
            qt_modules: "qt5compat qtimageformats"
            msvc_arch: x64
            output_dir: x86_64
    env:
      targetName: ainesmile
      
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          target: desktop
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: ${{ matrix.qt_modules }}
          cache: 'true'
          cache-key-prefix: 'install-qt-action-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}'
          aqtversion: '==3.0.1'
          
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: boost-property-tree uchardet
          triplet: x64-windows-release
          token: ${{ github.token }}
                              
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      
      - name: copy CMakeLists.txt
        shell: cmd
        run: |
          cd 3rdparty
          copy cmakes\CMakeLists.txt.lexilla lexilla\CMakeLists.txt
          copy cmakes\CMakeLists.txt.scintilla scintilla\CMakeLists.txt

      - name: patch
        shell: cmd
        run: |
          cd 3rdparty\lexilla
          git apply ..\lexilla.patch
          cd ..\..
          
      - name: Set up clang for Windows
        shell: cmd
        run: |
          mkdir llvm
          cd llvm
          curl.exe -o LLVM.exe -L ${{ matrix.clang_link }}
          7z.exe x LLVM.exe
          cd ..
                      
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          set PATH=%PATH%;%CD%\llvm\bin;%CD%\jom
          cd 3rdparty\scintilla\qt\ScintillaEdit
          python WidgetGen.py
          cd ..\..\..\..
          mkdir build
          cd build
          curl -o ninja.zip -sSL https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
          7z x ninja.zip
          cmake -DCMAKE_MAKE_PROGRAM=ninja.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release -DVCPKG_MANIFEST_MODE=OFF ..
          cmake --build . --parallel --verbose
          mkdir bin
          copy src\ainesmile\ainesmile.exe bin\
          windeployqt bin\ainesmile.exe
          cd ..
          
      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\bin
          name: ainesmile-clang-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ainesmile-intel-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          asset_name: ainesmile-clang-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true 
          
  win64-intel-msvc:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: win64_msvc2019_64
            qt_ver: 5.15.2
            qt_modules: ""
            msvc_arch: x64
            output_dir: x86_64
          - qt_arch: win64_msvc2019_64
            qt_ver: 6.5.2
            qt_modules: "qt5compat qtimageformats"
            msvc_arch: x64
            output_dir: x86_64
    env:
      targetName: ainesmile
      
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          target: desktop
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          modules: ${{ matrix.qt_modules }}
          cache: 'true'
          cache-key-prefix: 'install-qt-action-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}'
          aqtversion: '==3.0.1'
          
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: boost-property-tree uchardet
          triplet: x64-windows-release
          token: ${{ github.token }}
                    
      - name: cache intel install
        id: cache-install
        uses: actions/cache@v2
        with:
          path: |
              C:\Program Files (x86)\Intel\oneAPI\setvars-vcvarsall.bat
              C:\Program Files (x86)\Intel\oneAPI\compiler
          key: install-${{ env.CACHE_NUMBER }}-${{ env.WINDOWS_HPCKIT_URL }}-${{ env.WINDOWS_CPP_COMPONENTS }}-compiler-${{ hashFiles('**/scripts/cache_exclude_windows.sh') }}

      - name: install intel
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/oneapi-src/oneapi-ci.git oneapi-ci
          cd oneapi-ci
          scripts/install_windows.bat ${{ env.WINDOWS_HPCKIT_URL }} ${{ env.WINDOWS_CPP_COMPONENTS }}
          
      - name: restore registry on cache hit
        if: steps.cache-install.outputs.cache-hit == 'true'
        run:  |
          git clone --depth=1 https://github.com/oneapi-src/oneapi-ci.git oneapi-ci
          cd oneapi-ci
          scripts/restore_registry.bat ${{ env.COMPILER_VERSION }}
        
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      
      - name: copy CMakeLists.txt
        shell: cmd
        run: |
          cd 3rdparty
          copy cmakes\CMakeLists.txt.lexilla lexilla\CMakeLists.txt
          copy cmakes\CMakeLists.txt.scintilla scintilla\CMakeLists.txt

      - name: patch
        shell: cmd
        run: |
          cd 3rdparty\lexilla
          git apply ..\lexilla.patch
          cd ..\..
                      
      - name: build-intel-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          dir "C:\Program Files (x86)\Intel\oneAPI\compiler"
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          call "C:\Program Files (x86)\Intel\oneAPI\compiler\${{ env.COMPILER_VERSION }}\env\vars.bat"
          set PATH="C:\Program Files (x86)\Intel\oneAPI\compiler\${{ env.COMPILER_VERSION }}\windows\bin-llvm\";%CD%\jom;%PATH%
          cd 3rdparty\scintilla\qt\ScintillaEdit
          python WidgetGen.py
          cd ..\..\..\..
          mkdir build
          cd build
          curl -o ninja.zip -sSL https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
          7z x ninja.zip
          cmake -DCMAKE_MAKE_PROGRAM=ninja.exe -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icx -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release -DVCPKG_MANIFEST_MODE=OFF ..
          cmake --build . --parallel --verbose
          mkdir bin
          copy src\ainesmile\ainesmile.exe bin\
          windeployqt bin\ainesmile.exe
          cd ..
          
      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\bin
          name: ainesmile-intel-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ainesmile-intel-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          asset_name: ainesmile-intel-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true 

  win64-mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: ucrt64_qt5-gcc
            mingw_arch: UCRT64 
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            qt_build: qt5
            qt_dir: /ucrt64/lib/cmake/Qt5
            cmake_prefix_path: /ucrt64
          - qt_arch: ucrt64_qt5-static-gcc
            mingw_arch: UCRT64 
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            qt_build: qt5-static
            qt_dir: /ucrt64/qt5-static/lib/cmake/Qt5
            cmake_prefix_path: /ucrt64/qt5-static
          - qt_arch: clang64_qt5-clang
            mingw_arch: CLANG64 
            mingw_prefix: mingw-w64-clang-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            qt_build: qt5
            qt_dir: /clang64/lib/cmake/Qt5
            cmake_prefix_path: /clang64
          - qt_arch: clang64_qt5-static-clang
            mingw_arch: CLANG64 
            mingw_prefix: mingw-w64-clang-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            qt_build: qt5-static
            qt_dir: /clang64/qt5-static/lib/cmake/Qt5
            cmake_prefix_path: /clang64/qt5-static
          - qt_arch: ucrt64_qt6-gcc
            mingw_arch: UCRT64 
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            qt_build: qt6
            qt_dir: /ucrt64/lib/cmake/Qt6
            cmake_prefix_path: /ucrt64
          - qt_arch: clang64_qt6-clang
            mingw_arch: CLANG64 
            mingw_prefix: mingw-w64-clang-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            qt_build: qt6
            qt_dir: /clang64/lib/cmake/Qt6
            cmake_prefix_path: /clang64
          - qt_arch: ucrt64_qt6-static-gcc
            mingw_arch: UCRT64 
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            c: gcc
            cxx: g++
            qt_build: qt6-static
            qt_dir: /ucrt64/qt6-static/lib/cmake/Qt6
            cmake_prefix_path: /ucrt64/qt6-static
          - qt_arch: clang64_qt6-static-clang
            mingw_arch: CLANG64 
            mingw_prefix: mingw-w64-clang-x86_64
            toolchains: clang
            c: clang
            cxx: clang++
            qt_build: qt6-static
            qt_dir: /clang64/qt6-static/lib/cmake/Qt6
            cmake_prefix_path: /clang64/qt6-static
    env:
      targetName: ainesmile
      
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install:  ${{ matrix.mingw_prefix }}-boost ${{ matrix.mingw_prefix }}-cmake ${{ matrix.mingw_prefix }}-ninja ${{ matrix.mingw_prefix }}-${{ matrix.toolchains }} ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-${{ matrix.qt_build }} ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd ${{ matrix.mingw_prefix }}-libb2 ${{ matrix.mingw_prefix }}-jasper ${{ matrix.mingw_prefix }}-uchardet

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
          submodules: true
          
      - run: |
          git clone https://github.com/missdeer/mingwdeployqt.git
          
      - name: Build mingwdeployqt
        shell: msys2 {0}
        run: |
          cd mingwdeployqt
          mkdir build
          cd build
          env PATH=/${{ matrix.mingw_arch }}/${{ matrix.qt_build }}/bin:/${{ matrix.mingw_arch }}/bin cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja ..
          ninja
          cp mingwdeployqt.exe /${{ matrix.mingw_arch }}/bin/
          cd ../..

      - name: copy CMakeLists.txt
        shell: msys2 {0}
        run: |
          cd 3rdparty
          cp cmakes/CMakeLists.txt.lexilla lexilla/CMakeLists.txt
          cp cmakes/CMakeLists.txt.scintilla scintilla/CMakeLists.txt

      - name: patch 3rdparty
        shell: cmd
        run: |
          cd 3rdparty\lexilla
          git apply ..\lexilla.patch

      - name: prepare Scintilla
        shell: cmd
        run: |
          cd 3rdparty\scintilla\qt\ScintillaEdit
          python WidgetGen.py
          cd ..\..\..\..

      - name: build
        shell: msys2 {0}
        run: |
          ./pre-build.sh
          mkdir build
          cd build
          env PATH=/${{ matrix.mingw_arch }}/${{ matrix.qt_build }}/bin:/${{ matrix.mingw_arch }}/bin cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DQT_DIR=${{ matrix.qt_dir }} -DCMAKE_PREFIX_PATH=${{ matrix.cmake_prefix_path }} -G Ninja ..
          env PATH=/${{ matrix.mingw_arch }}/${{ matrix.qt_build }}/bin:/${{ matrix.mingw_arch }}/bin cmake --build . --parallel --verbose
          mkdir bin
          cp src/ainesmile/ainesmile.exe ./bin/
          env PATH=/${{ matrix.mingw_arch }}/bin mingwdeployqt.exe bin/ainesmile.exe
          
      - name: upload executable artifact
        uses: actions/upload-artifact@v1
        with:
          path: build\bin
          name: ainesmile-${{ matrix.qt_arch }}

      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: ainesmile-${{ matrix.qt_arch }}.zip
          asset_name: ainesmile-${{ matrix.qt_arch }}.zip
          tag: ${{ github.ref }}
          overwrite: true 

  macOS:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [6.5.2]
        qt_arch: [clang_64]
    env:
      targetName: ainesmile
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          modules: "qt5compat qtimageformats"
          aqtversion: '==3.0.1'
        
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
      
      - name: patch 3rdparty
        run: |
          cd 3rdparty
          cp cmakes/CMakeLists.txt.lexilla lexilla/CMakeLists.txt
          cp cmakes/CMakeLists.txt.scintilla scintilla/CMakeLists.txt
          cd lexilla
          git apply ../lexilla.patch
          cd ../..
      
      - name: build macos
        run: |
          brew install boost uchardet ninja
          ./pre-build.sh
          cd 3rdparty/scintilla/qt/ScintillaEdit
          python WidgetGen.py
          cd ../../../..
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
          cmake --build . --parallel --verbose
          cd ..
          
      - name: package
        run: |
          macdeployqt "build/src/ainesmile/ainesmile.app" -qmldir=. -verbose=1 -dmg
        
